# -*- mode: yaml -*-

environment:
  matrix:
    - CONFIG: win_python3.6
      CONDA_INSTALL_LOCN: C:\Miniconda36-x64

platform:
    - x64

install:
    # Cygwin's git breaks conda-build
    - cmd: rmdir C:\cygwin /s /q

    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda.exe update --yes --quiet conda

    - cmd: set PYTHONUNBUFFERED=1

    # Create environment
    - cmd: conda env create -f workshop.yml

# Skip .NET project specific build phase.
build: off

before_test:
    - conda activate workshop

test_script:
    - python tests/test_assembly_stack.py
